openapi: 3.1.0
info:
  title: MarketDataAPI.com - Path Parameters
  version: '1'

components:
  parameters:
    SecurityIdentifierPathParam:
      name: identifier
      in: path
      required: true
      schema:
        $ref: '../schemas/security.yaml#/components/schemas/SecurityIdentifier'
