openapi: 3.1.0
info:
  title: MarketDataAPI.com - Exchange Schemas
  version: '1'

components:
  schemas:
    MIC:
      type: string
      description: ISO 10383 Market Identifier Codes
      enum:
        - XNYS  # NYSE
        - XNAS  # NASDAQ
        - XLON  # LSE
        - XPAR  # EURONEXT

    ExchangeName:
      type: string
      description: Exchange name
      enum:
        - NYSE
        - NASDAQ
        - LSE
        - EURONEXT

    Exchange:
      type: object
      required:
        - mic
        - name
      properties:
        mic:
          $ref: '#/components/schemas/MIC'
          description: Market Identifier Code
          example: 'XNAS'
        name:
          $ref: '#/components/schemas/ExchangeName'
          description: Exchange name
          example: 'NASDAQ'
      example:
        mic: 'XNAS'
        name: 'NASDAQ'