openapi: 3.1.0
info:
  title: MarketDataAPI.com - GICS Sub-Industry Schemas
  version: '1'

components:
  schemas:
    SubIndustryCode:
      type: string
      description: GICS sub-industry code (8-digit)
      enum:
        # Energy (10)
        - '10101010'  # Oil & Gas Drilling
        - '10101020'  # Oil & Gas Equipment & Services
        - '10102010'  # Integrated Oil & Gas
        - '10102020'  # Oil & Gas Exploration & Production
        - '10102030'  # Oil & Gas Refining & Marketing
        - '10102040'  # Oil & Gas Storage & Transportation
        - '10102050'  # Coal & Consumable Fuels
        
        # Materials (15)
        - '15101010'  # Commodity Chemicals
        - '15101020'  # Diversified Chemicals
        - '15101030'  # Fertilizers & Agricultural Chemicals
        - '15101040'  # Industrial Gases
        - '15101050'  # Specialty Chemicals
        - '15102010'  # Construction Materials
        - '15103010'  # Metal, Glass & Plastic Containers
        - '15103020'  # Paper & Plastic Packaging Products & Materials
        - '15104010'  # Aluminum
        - '15104020'  # Diversified Metals & Mining
        - '15104025'  # Copper
        - '15104030'  # Gold
        - '15104040'  # Precious Metals & Minerals
        - '15104045'  # Silver
        - '15104050'  # Steel
        - '15105010'  # Forest Products
        - '15105020'  # Paper Products
        
        # Industrials (20)
        - '20101010'  # Aerospace & Defense
        - '20102010'  # Building Products
        - '20103010'  # Construction & Engineering
        - '20104010'  # Electrical Components & Equipment
        - '20104020'  # Heavy Electrical Equipment
        - '20105010'  # Industrial Conglomerates
        - '20106010'  # Construction Machinery & Heavy Transportation Equipment
        - '20106015'  # Agricultural & Farm Machinery
        - '20106020'  # Industrial Machinery & Supplies & Components
        - '20107010'  # Trading Companies & Distributors
        - '20201010'  # Commercial Printing
        - '20201050'  # Environmental & Facilities Services
        - '20201060'  # Office Services & Supplies
        - '20201070'  # Diversified Support Services
        - '20201080'  # Security & Alarm Services
        - '20202010'  # Human Resource & Employment Services
        - '20202020'  # Research & Consulting Services
        - '20202030'  # Data Processing & Outsourced Services
        - '20301010'  # Air Freight & Logistics
        - '20302010'  # Passenger Airlines
        - '20303010'  # Marine Transportation
        - '20304010'  # Rail Transportation
        - '20304030'  # Cargo Ground Transportation
        - '20304040'  # Passenger Ground Transportation
        - '20305010'  # Airport Services
        - '20305020'  # Highways & Railtracks
        - '20305030'  # Marine Ports & Services
        
        # Consumer Discretionary (25)
        - '25101010'  # Automotive Parts & Equipment
        - '25101020'  # Tires & Rubber
        - '25102010'  # Automobile Manufacturers
        - '25102020'  # Motorcycle Manufacturers
        - '25201010'  # Consumer Electronics
        - '25201020'  # Home Furnishings
        - '25201030'  # Homebuilding
        - '25201040'  # Household Appliances
        - '25201050'  # Housewares & Specialties
        - '25202010'  # Leisure Products
        - '25203010'  # Apparel, Accessories & Luxury Goods
        - '25203020'  # Footwear
        - '25203030'  # Textiles
        - '25301010'  # Casinos & Gaming
        - '25301020'  # Hotels, Resorts & Cruise Lines
        - '25301030'  # Leisure Facilities
        - '25301040'  # Restaurants
        - '25302010'  # Education Services
        - '25302020'  # Specialized Consumer Services
        - '25501010'  # Distributors
        - '25503030'  # Broadline Retail
        - '25504010'  # Apparel Retail
        - '25504020'  # Computer & Electronics Retail
        - '25504030'  # Home Improvement Retail
        - '25504040'  # Other Specialty Retail
        - '25504050'  # Automotive Retail
        - '25504060'  # Homefurnishing Retail
        
        # Consumer Staples (30)
        - '30101010'  # Drug Retail
        - '30101020'  # Food Distributors
        - '30101030'  # Food Retail
        - '30101040'  # Consumer Staples Merchandise Retail
        - '30201010'  # Brewers
        - '30201020'  # Distillers & Vintners
        - '30201030'  # Soft Drinks & Non-alcoholic Beverages
        - '30202010'  # Agricultural Products & Services
        - '30202030'  # Packaged Foods & Meats
        - '30203010'  # Tobacco
        - '30301010'  # Household Products
        - '30302010'  # Personal Care Products
        
        # Health Care (35)
        - '35101010'  # Health Care Equipment
        - '35101020'  # Health Care Supplies
        - '35102010'  # Health Care Distributors
        - '35102015'  # Health Care Services
        - '35102020'  # Health Care Facilities
        - '35102030'  # Managed Health Care
        - '35103010'  # Health Care Technology
        - '35201010'  # Biotechnology
        - '35202010'  # Pharmaceuticals
        - '35203010'  # Life Sciences Tools & Services
        
        # Financials (40)
        - '40101010'  # Diversified Banks
        - '40101015'  # Regional Banks
        - '40201020'  # Diversified Financial Services
        - '40201030'  # Multi-Sector Holdings
        - '40201040'  # Specialized Finance
        - '40201050'  # Commercial & Residential Mortgage Finance
        - '40201060'  # Transaction & Payment Processing Services
        - '40202010'  # Consumer Finance
        - '40203010'  # Asset Management & Custody Banks
        - '40203020'  # Investment Banking & Brokerage
        - '40203030'  # Diversified Capital Markets
        - '40203040'  # Financial Exchanges & Data
        - '40204010'  # Mortgage REITs
        - '40301010'  # Insurance Brokers
        - '40301020'  # Life & Health Insurance
        - '40301030'  # Multi-line Insurance
        - '40301040'  # Property & Casualty Insurance
        - '40301050'  # Reinsurance
        
        # Information Technology (45)
        - '45102010'  # IT Consulting & Other Services
        - '45102030'  # Internet Services & Infrastructure
        - '45103010'  # Application Software
        - '45103020'  # Systems Software
        - '45201020'  # Communications Equipment
        - '45202030'  # Technology Hardware, Storage & Peripherals
        - '45203010'  # Electronic Equipment & Instruments
        - '45203015'  # Electronic Components
        - '45203020'  # Electronic Manufacturing Services
        - '45203030'  # Technology Distributors
        - '45301010'  # Semiconductor Materials & Equipment
        - '45301020'  # Semiconductors
        
        # Communication Services (50)
        - '50101010'  # Alternative Carriers
        - '50101020'  # Integrated Telecommunication Services
        - '50102010'  # Wireless Telecommunication Services
        - '50201010'  # Advertising
        - '50201020'  # Broadcasting
        - '50201030'  # Cable & Satellite
        - '50201040'  # Publishing
        - '50202010'  # Movies & Entertainment
        - '50202020'  # Interactive Home Entertainment
        - '50203010'  # Interactive Media & Services
        
        # Utilities (55)
        - '55101010'  # Electric Utilities
        - '55102010'  # Gas Utilities
        - '55103010'  # Multi-Utilities
        - '55104010'  # Water Utilities
        - '55105010'  # Independent Power Producers & Energy Traders
        - '55105020'  # Renewable Electricity
        
        # Real Estate (60)
        - '60101010'  # Diversified REITs
        - '60102510'  # Industrial REITs
        - '60103010'  # Hotel & Resort REITs
        - '60104010'  # Office REITs
        - '60105010'  # Health Care REITs
        - '60106010'  # Multi-Family Residential REITs
        - '60106020'  # Single-Family Residential REITs
        - '60107010'  # Retail REITs
        - '60108010'  # Other Specialized REITs
        - '60108020'  # Self-Storage REITs
        - '60108030'  # Telecom Tower REITs
        - '60108040'  # Timber REITs
        - '60108050'  # Data Center REITs
        - '60201010'  # Diversified Real Estate Activities
        - '60201020'  # Real Estate Operating Companies
        - '60201030'  # Real Estate Development
        - '60201040'  # Real Estate Services

    SubIndustryName:
      type: string
      description: GICS sub-industry name
      enum:
        # Energy (10)
        - 'Oil & Gas Drilling'
        - 'Oil & Gas Equipment & Services'
        - 'Integrated Oil & Gas'
        - 'Oil & Gas Exploration & Production'
        - 'Oil & Gas Refining & Marketing'
        - 'Oil & Gas Storage & Transportation'
        - 'Coal & Consumable Fuels'
        
        # Materials (15)
        - 'Commodity Chemicals'
        - 'Diversified Chemicals'
        - 'Fertilizers & Agricultural Chemicals'
        - 'Industrial Gases'
        - 'Specialty Chemicals'
        - 'Construction Materials'
        - 'Metal, Glass & Plastic Containers'
        - 'Paper & Plastic Packaging Products & Materials'
        - 'Aluminum'
        - 'Diversified Metals & Mining'
        - 'Copper'
        - 'Gold'
        - 'Precious Metals & Minerals'
        - 'Silver'
        - 'Steel'
        - 'Forest Products'
        - 'Paper Products'
        
        # Industrials (20)
        - 'Aerospace & Defense'
        - 'Building Products'
        - 'Construction & Engineering'
        - 'Electrical Components & Equipment'
        - 'Heavy Electrical Equipment'
        - 'Industrial Conglomerates'
        - 'Construction Machinery & Heavy Transportation Equipment'
        - 'Agricultural & Farm Machinery'
        - 'Industrial Machinery & Supplies & Components'
        - 'Trading Companies & Distributors'
        - 'Commercial Printing'
        - 'Environmental & Facilities Services'
        - 'Office Services & Supplies'
        - 'Diversified Support Services'
        - 'Security & Alarm Services'
        - 'Human Resource & Employment Services'
        - 'Research & Consulting Services'
        - 'Data Processing & Outsourced Services'
        - 'Air Freight & Logistics'
        - 'Passenger Airlines'
        - 'Marine Transportation'
        - 'Rail Transportation'
        - 'Cargo Ground Transportation'
        - 'Passenger Ground Transportation'
        - 'Airport Services'
        - 'Highways & Railtracks'
        - 'Marine Ports & Services'
        
        # Consumer Discretionary (25)
        - 'Automotive Parts & Equipment'
        - 'Tires & Rubber'
        - 'Automobile Manufacturers'
        - 'Motorcycle Manufacturers'
        - 'Consumer Electronics'
        - 'Home Furnishings'
        - 'Homebuilding'
        - 'Household Appliances'
        - 'Housewares & Specialties'
        - 'Leisure Products'
        - 'Apparel, Accessories & Luxury Goods'
        - 'Footwear'
        - 'Textiles'
        - 'Casinos & Gaming'
        - 'Hotels, Resorts & Cruise Lines'
        - 'Leisure Facilities'
        - 'Restaurants'
        - 'Education Services'
        - 'Specialized Consumer Services'
        - 'Distributors'
        - 'Broadline Retail'
        - 'Apparel Retail'
        - 'Computer & Electronics Retail'
        - 'Home Improvement Retail'
        - 'Other Specialty Retail'
        - 'Automotive Retail'
        - 'Homefurnishing Retail'
        
        # Consumer Staples (30)
        - 'Drug Retail'
        - 'Food Distributors'
        - 'Food Retail'
        - 'Consumer Staples Merchandise Retail'
        - 'Brewers'
        - 'Distillers & Vintners'
        - 'Soft Drinks & Non-alcoholic Beverages'
        - 'Agricultural Products & Services'
        - 'Packaged Foods & Meats'
        - 'Tobacco'
        - 'Household Products'
        - 'Personal Care Products'
        
        # Health Care (35)
        - 'Health Care Equipment'
        - 'Health Care Supplies'
        - 'Health Care Distributors'
        - 'Health Care Services'
        - 'Health Care Facilities'
        - 'Managed Health Care'
        - 'Health Care Technology'
        - 'Biotechnology'
        - 'Pharmaceuticals'
        - 'Life Sciences Tools & Services'
        
        # Financials (40)
        - 'Diversified Banks'
        - 'Regional Banks'
        - 'Diversified Financial Services'
        - 'Multi-Sector Holdings'
        - 'Specialized Finance'
        - 'Commercial & Residential Mortgage Finance'
        - 'Transaction & Payment Processing Services'
        - 'Consumer Finance'
        - 'Asset Management & Custody Banks'
        - 'Investment Banking & Brokerage'
        - 'Diversified Capital Markets'
        - 'Financial Exchanges & Data'
        - 'Mortgage REITs'
        - 'Insurance Brokers'
        - 'Life & Health Insurance'
        - 'Multi-line Insurance'
        - 'Property & Casualty Insurance'
        - 'Reinsurance'
        
        # Information Technology (45)
        - 'IT Consulting & Other Services'
        - 'Internet Services & Infrastructure'
        - 'Application Software'
        - 'Systems Software'
        - 'Communications Equipment'
        - 'Technology Hardware, Storage & Peripherals'
        - 'Electronic Equipment & Instruments'
        - 'Electronic Components'
        - 'Electronic Manufacturing Services'
        - 'Technology Distributors'
        - 'Semiconductor Materials & Equipment'
        - 'Semiconductors'
        
        # Communication Services (50)
        - 'Alternative Carriers'
        - 'Integrated Telecommunication Services'
        - 'Wireless Telecommunication Services'
        - 'Advertising'
        - 'Broadcasting'
        - 'Cable & Satellite'
        - 'Publishing'
        - 'Movies & Entertainment'
        - 'Interactive Home Entertainment'
        - 'Interactive Media & Services'
        
        # Utilities (55)
        - 'Electric Utilities'
        - 'Gas Utilities'
        - 'Multi-Utilities'
        - 'Water Utilities'
        - 'Independent Power Producers & Energy Traders'
        - 'Renewable Electricity'
        
        # Real Estate (60)
        - 'Diversified REITs'
        - 'Industrial REITs'
        - 'Hotel & Resort REITs'
        - 'Office REITs'
        - 'Health Care REITs'
        - 'Multi-Family Residential REITs'
        - 'Single-Family Residential REITs'
        - 'Retail REITs'
        - 'Other Specialized REITs'
        - 'Self-Storage REITs'
        - 'Telecom Tower REITs'
        - 'Timber REITs'
        - 'Data Center REITs'
        - 'Diversified Real Estate Activities'
        - 'Real Estate Operating Companies'
        - 'Real Estate Development'
        - 'Real Estate Services'

    SubIndustry:
      type: object
      required: [ code, name ]
      properties:
        code:
          $ref: '#/components/schemas/SubIndustryCode'
        name:
          $ref: '#/components/schemas/SubIndustryName'
      example:
        code: '45202030'
        name: 'Technology Hardware, Storage & Peripherals'