openapi: 3.1.0
info:
  title: MarketDataAPI.com - GICS Schemas
  version: '1'

components:
  schemas:
    GICS:
      type: object
      description: The GICS classification of an securities
      required: [ sector, industry_group, industry, version ]
      properties:
        sector:
          $ref: './gics-sector.yaml#/components/schemas/Sector'
        industry_group:
          $ref: './gics-industry-group.yaml#/components/schemas/IndustryGroup'
        industry:
          $ref: './gics-industry.yaml#/components/schemas/Industry'
        sub_industry:
          $ref: './gics-sub-industry.yaml#/components/schemas/SubIndustry'
          description: Optional sub-industry classification
        version:
          type: string
          format: date
          description: Date of GICS standard applied
          example: 2026-01-01
      example:
        sector:
          code: '45'
          name: 'Information Technology'
        industry_group:
          code: '4520'
          name: 'Technology Hardware & Equipment'
        industry:
          code: '452020'
          name: 'Technology Hardware, Storage & Peripherals'
        sub_industry:
          code: '45202030'
          name: 'Technology Hardware, Storage & Peripherals'
        version: '2026-01-01'